<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dntysy9ts/image/upload/v1554496363/__234_903_662_9608__20161012_151005.png" alt="Mark Essien">
                        <h6>Kusimo Ibrahim</h6>
                        <p>Aspiring Full-Stack developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/ibkush" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ibkush" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://ibkush.home.blog/" target="_blank"<i class="fab fa-wordpress fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I'm Kusimo Ibrahim, a Chemical Engineer with little to no experience in web/app development but eager to learn. Getting to this level already feels like a success</p>
                        <br />
                        <h6>Skills(in view</h6>
                        <p>JavaScript | CSS | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
